"""
Depth-Anything-3D: 3D viewing extensions for Video-Depth-Anything.

This package provides interactive 3D mesh visualization and real-time rendering
capabilities for depth maps generated by Video-Depth-Anything.

Main Features:
- Real-time 3D mesh viewing from webcam
- Screen capture with 3D visualization
- 2.5D parallax effects for creative depth display
- Interactive camera controls
- Performance-optimized rendering

Quick Start:
    >>> from da3d.viewing import view_depth_3d
    >>> view_depth_3d("image.jpg", "depth.png")

CLI Usage:
    $ da3d webcam3d              # View yourself in 3D
    $ da3d screen3d-viewer       # Capture screen in 3D
    $ da3d view3d image.jpg depth.png  # View static depth maps
"""

from .viewing import DepthMeshViewer, RealTime3DViewer, view_depth_3d
from .projection import DepthProjector, InteractiveParallaxController

__version__ = "0.1.0"
__author__ = "Video-Depth-Anything-3D Contributors"
__license__ = "Apache-2.0"

__all__ = [
    # Viewing
    "DepthMeshViewer",
    "RealTime3DViewer",
    "view_depth_3d",
    # Projection
    "DepthProjector",
    "InteractiveParallaxController",
    # Metadata
    "__version__",
]
